apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: my-workflow

on:
  push:
    branches:
      - feature/your-feature-name

jobs:
  build-and-run:
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Install dependencies and Run app.js
        uses: docker://node:18-alpine
        shell: sh
        env:
          NODE_ENV: production
        run: |
          set -e
          echo "Installing dependencies..."
          npm install
          echo "Running app.js..."
          node app.js